version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    # command: bash
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db